# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletinApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('posted_by', models.CharField(max_length=100)),
                ('replied_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletinApp.BulletinPost')),
            ],
        ),
    ]
