# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('sent_by', models.CharField(max_length=100)),
                ('sent_to', models.CharField(max_length=100)),
                ('urgency', models.IntegerField()),
            ],
        ),
    ]
